-- Habilita extensão para uso de UUID
create extension if not exists "uuid-ossp";

-- 1. Tabela de Perfis (substitui a antiga users)
-- Vinculada automaticamente ao auth.users do Supabase
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text not null,
  name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Trigger para criar perfil automaticamente quando um usuário se cadastra
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, name)
  values (new.id, new.email, new.raw_user_meta_data->>'name');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 2. Tabela de Provedores (Providers)
-- Armazena as chaves de API. Em produção, use o Supabase Vault ou criptografia.
create table public.providers (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  provider_name text not null, -- 'vultr', 'digitalocean', 'linode'
  api_key text not null, -- IMPORTANTE: Considere criptografar isso antes de salvar
  label text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS para Providers
alter table public.providers enable row level security;

create policy "Usuários podem ver apenas seus providers"
  on public.providers for select
  using ( auth.uid() = user_id );

create policy "Usuários podem criar seus providers"
  on public.providers for insert
  with check ( auth.uid() = user_id );

create policy "Usuários podem deletar seus providers"
  on public.providers for delete
  using ( auth.uid() = user_id );

-- 3. Cache de Servidores
-- user_id adicionado para facilitar RLS sem joins complexos
create table public.servers_cache (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  provider_id bigint references public.providers(id) on delete cascade,
  external_id text not null,
  name text,
  ip_address text,
  status text, -- 'active', 'pending', 'off'
  specs jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  last_synced timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS para Servers
alter table public.servers_cache enable row level security;

create policy "Usuários podem ver seus servidores"
  on public.servers_cache for select
  using ( auth.uid() = user_id );

create policy "Usuários podem inserir servidores"
  on public.servers_cache for insert
  with check ( auth.uid() = user_id );

create policy "Usuários podem atualizar seus servidores"
  on public.servers_cache for update
  using ( auth.uid() = user_id );

create policy "Usuários podem deletar seus servidores"
  on public.servers_cache for delete
  using ( auth.uid() = user_id );

-- 4. Sites
create table public.sites (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  server_id bigint references public.servers_cache(id) on delete cascade,
  domain text not null,
  platform text default 'php',
  php_version text,
  status text default 'provisioning',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  enable_temp_url boolean default false
);

-- RLS para Sites
alter table public.sites enable row level security;

create policy "Usuários gerenciam seus sites"
  on public.sites for all
  using ( auth.uid() = user_id );
