-- Limpa todas as tabelas do sistema (remove todos os dados)
TRUNCATE TABLE tickets RESTART IDENTITY CASCADE;
TRUNCATE TABLE revenue RESTART IDENTITY CASCADE;
TRUNCATE TABLE sites RESTART IDENTITY CASCADE;
TRUNCATE TABLE servers_cache RESTART IDENTITY CASCADE;
TRUNCATE TABLE providers RESTART IDENTITY CASCADE;
TRUNCATE TABLE users RESTART IDENTITY CASCADE;
